version: '3.8'

services:
  chat_service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /home/ubuntu/.cache/modelscope/hub/models/qwen/Qwen2___5-72B-Instruct-GPTQ-Int4:/app/models
      - ./src:/app/src

    # 添加共享内存配置
    shm_size: '16gb'  # 分配16GB共享内存，可根据需要调整

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3